### ISSUE TITLE
mct.out offset warning

### ISSUE THREAD

**Issue by AnnieConway** [biometryhub/BiometryTraining#37]
Getting a warning message about the offset even when I manually set the offset.

**Comment by rogerssam** [comment]
This is problematic because of the default value of `offset = 0`.
We can't check if it's missing, because it has a default value. We could check if `offset == 0` and show the warning in those cases, but this may be annoying/confusing if users are making use of the default value.
Possibly change default value? Or only show the warning once every <time period>?

**Comment by rogerssam** [comment]
Look at adding a "footer" (as per asreml predict method) to display offset and transformation values if set

**Comment by rogerssam** [comment]
Offset as NA, and print a nice error if `trans != NA`.

**Comment by rogerssam** [comment]
Fixed in dev
