### ISSUE TITLE
Switch to Object oriented programming

### ISSUE THREAD

**Issue by rogerssam** [biometryhub/BiometryTraining#60]
This would greatly simplify things from a user perspective. We can have `plot()` methods for `design()` and `mct.out()` functions which automatically create the desired plot, but the user just has the data frame or list they can work with.

**Comment by emitanaka** [comment]
Just a note that community convention is that `plot` = base plot where as `autoplot` = ggplot, so you may like to factor that in if going with `plot`

**Comment by rogerssam** [comment]
Thanks for the heads up @emitanaka

**Comment by rogerssam** [comment]
Need to add print methods for `mct.out()` and possibly `design()` as well

**Comment by emitanaka** [comment]
* I'd avoid using `.` in function names and maybe replace it with `_`. R uses `.` to invoke S3 methods, e.g. `print(x)` is actually calling `print.data.frame(x)` if `x` is a `data.frame`.  
* Also I wonder if it's worthwhile being more explicit in function names than calling it `mct.out`? Like `multiple_comparisons`?
* For print methods, you may just need to change `format` rather than `print`.

**Comment by rogerssam** [comment]
Thanks Emi.

> * I'd avoid using `.` in function names and maybe replace it with `_`. R uses `.` to invoke S3 methods, e.g. `print(x)` is actually calling `print.data.frame(x)` if `x` is a `data.frame`.

Yes, I plan to, but the current versions will be around for a while because there's a level of historical inertia now that will take time to overcome.

> * Also I wonder if it's worthwhile being more explicit in function names than calling it `mct.out`? Like `multiple_comparisons`?

Yes probably a good idea.
